### ISSUE TITLE
Restore jobs from redis on restart

### ISSUE THREAD

**Issue by xtazz** [lykmapipo/kue-scheduler#11]
It would be nice to restore and reschedule jobs after failure or restart

**Comment by lykmapipo** [comment]
@xtazz 

+1

**Comment by arvindr21** [comment]
+1

**Comment by lykmapipo** [comment]
I have been in tight schedule. I will pull it soon

**Comment by lykmapipo** [comment]
@xtazz and @arvindr21 

kue-scheduler added ability for unique jobs and since all job work is maintained with kue core, now restore and reschedule is achieved implicitly.

Check [unique every job](https://github.com/lykmapipo/kue-scheduler#schedule-a-unique-job-to-run-every-after-specified-time-interval) to achieve this.
