### ISSUE TITLE
Unique recurring jobs are duplicated when they are restored

### ISSUE THREAD

**Issue by schmod** [lykmapipo/kue-scheduler#90]
When queues are restored, we sometimes end up with more instances of a unique job than we started with.

For example, a job that is scheduled to run every 2 seconds ends up running every second when we restore its queue:

```js
const kue = require('./index');

const Queue1 = kue.createQueue();
Queue1.clear();

var backoff = {
  delay: 60000,
  type: 'fixed'
};

var job = Queue1
  .createJob('unique_every', {})
  .attempts(3)
  .backoff(backoff)
  .priority('normal')
  .unique('every_mail');

Queue1.every('2 seconds', job);

Queue1.process('unique_every', function (job, finalize) {
  console.log('Queue 1: ' + new Date());
  finalize();
});

setTimeout(function() {
  const Queue2 = kue.createQueue();
  Queue2.restore();
  Queue2.process('unique_every', function (job, finalize) {
    console.log('Queue 2: ' + new Date());
    finalize();
  });
}, 3000);
```

Output:

```
Queue 1: Mon Mar 27 2017 12:14:15 GMT-0400 (EDT)
Queue 2: Mon Mar 27 2017 12:14:16 GMT-0400 (EDT)
Queue 1: Mon Mar 27 2017 12:14:17 GMT-0400 (EDT)
Queue 2: Mon Mar 27 2017 12:14:18 GMT-0400 (EDT)
Queue 1: Mon Mar 27 2017 12:14:19 GMT-0400 (EDT)
Queue 2: Mon Mar 27 2017 12:14:20 GMT-0400 (EDT)
```

Note that the job is clearly running every second instead of every 2 seconds.

**Comment by lykmapipo** [comment]
@schmod To test this.

1. Use [https://github.com/lykmapipo/kue-scheduler/blob/master/test/restore.spec.js](https://github.com/lykmapipo/kue-scheduler/blob/master/test/restore.spec.js)

2. Create a new `describe block`.
  - Inside that block ensure you have [shutdown kue sceduler](https://github.com/lykmapipo/kue-scheduler/blob/master/test/restore.spec.js#L36)
- [Clear Schedules](https://github.com/lykmapipo/kue-scheduler/blob/master/test/schedule/every.spec.js#L15)
 - [Restart scheduler](https://github.com/lykmapipo/kue-scheduler/blob/master/test/schedule/every.spec.js#L14)
- Schedule single every job(2 second every job for simplicity)
- [Shutdown kue-scheduler](https://github.com/lykmapipo/kue-scheduler/blob/master/test/restore.spec.js#L36)
- [Attach listener for listen once restore finished](https://github.com/lykmapipo/kue-scheduler#restore-error)
- [Restart scheduler after 4 second](https://github.com/lykmapipo/kue-scheduler/blob/master/test/schedule/every.spec.js#L14)
- Assert expected behavior based on the scheduled job which can be obtain by listen to jib complete event as specified in kue.

Lets start with that then we will improve for other scenarios.

Hope it helps.
